[theme]
base="light"  # Ou "dark"
primaryColor="#1E90FF"  # Cor principal
backgroundColor="#F0F2F6"  # Cor de fundo
secondaryBackgroundColor="#084d6e"  # Cor do fundo da barra lateral
textColor="#000000"  # Cor do texto
font="sans serif"  # Fonte utilizada